### PR TITLE
Binary Search Tree in cpp

### PR DESCRIPTION
**Pull request by VaishnaviJha786**

### CODE REVIEW

**Comment by zahinekbal** [comment]
again you didn't check the file format

**Comment by VaishnaviJha786** [comment]
I think file formats are right.
Both are in .cpp 
I have added BST and Quick Sort

**Comment by zahinekbal** [comment]
For quick sort it is not right go to the issues page nd check the description box

**Comment by VaishnaviJha786** [comment]
okay

**Pull request closed without merging**
