### PR TITLE
Added BinarySearchTree.java, TapMusic - FrontEnd, Updated ReadMe.md

### PR DESCRIPTION
**Pull request by ahmedashfaq027**

### CODE REVIEW

**Comment by zahinekbal** [comment]
Please add your image in image folder nd update readme.md file it is all for contributors 
do this then only i will be able to merge this..
Check this
#90 (comment)

**Comment by ahmedashfaq027** [comment]
Hey, I cannot get your repo because of this invalid path: 'Standard Questions/Algebra/Number-theoretic functions/Euler's totient function/SPOJ #4141 "Euler Totient Function" [Difficulty: CakeWalk].cpp'

Can you correct it? (It's because of the apostrophe in Euler's)

**Comment by zahinekbal** [comment]
> Hey, I cannot get your repo because of this invalid path: 'Standard Questions/Algebra/Number-theoretic functions/Euler's totient function/SPOJ #4141 "Euler Totient Function" [Difficulty: CakeWalk].cpp'
> 
> Can you correct it? (It's because of the apostrophe in Euler's)

I m not getting your point nd in my repo there is no folder of Questions/Algebra/Number-theoretic functions/Euler's totient function/SPOJ #4141 "Euler Totient Function

**Comment by zahinekbal** [comment]
Wait wait let me check one sec

**Comment by zahinekbal** [comment]
Actually I merged someone's PR that's y we are getting problem

**Comment by ahmedashfaq027** [comment]
cd 

> Actually I merged someone's PR that's y we are getting problem

alright!

**Comment by zahinekbal** [comment]
For now you can check new issues I have added

**Comment by ahmedashfaq027** [comment]
Thanks

**Comment by ahmedashfaq027** [comment]
Hey, Can you please review my PR? #93

**Comment by zahinekbal** [comment]
@ahmedashfaq027 you did wrong file format for binarytree
 BinarySearchTree.java

check my repo there is already BinarySearchTree/java   you hv to do that like did i.e:-
### BinarySearchTree/java/thenYourProgram.extention

**Comment by ahmedashfaq027** [comment]
Hi @zahinekbal,
My Bad, I'm so sorry about that!
I've now moved it! Can you review again?

**Comment by ahmedashfaq027** [comment]
Hey @zahinekbal ,
Can you please merge my PR?

**Pull request merged**
