### PR TITLE
Added sorting algorithms

### PR DESCRIPTION
**Pull request by sachin-611**
added sorting algorithms in correct file format

### CODE REVIEW

**Comment by sachin-611** [comment]
@zahinekbal now is it fine?

**Comment by zahinekbal** [comment]
> @zahinekbal now is it fine?

Yeep

**Comment by sachin-611** [comment]
> > @zahinekbal now is it fine?
> 
> Yeep

thank you so much :)
how may i contribute more let me know

**Comment by zahinekbal** [comment]
Yeah I will update my issues section or you can also create issue section nd start your making pr

**Pull request merged**
