### PR TITLE
Create Bass Militia front end site

### PR DESCRIPTION
**Pull request by samlaubscher**
I have added a multi page front end site for the Bass Militia Collective.

### CODE REVIEW

**Comment by samlaubscher** [comment]
There are issues with this, sorry I will update the files

**Comment by samlaubscher** [comment]
Files should now be ready to merge

**Comment by samlaubscher** [comment]
Added myself to contributors list :)

**Comment by zahinekbal** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
