### PR TITLE
Sai pranay

### PR DESCRIPTION
**Pull request by saipranay47**
Added UniqueNumberBitwise.cpp. 
And added my profile in readme.md. 

If there are any problems in the code suggest me I will resolve them, 

If you are satisfied with my code then I will make more pull requests. 

I had down this for hacktoberfest2020.

### CODE REVIEW

**Comment by zahinekbal** [comment]
> Added UniqueNumberBitwise.cpp.
> And added my profile in readme.md.
> 
> If there are any problems in the code suggest me I will resolve them,
> 
> If you are satisfied with my code then I will make more pull requests.
> 
> I had down this for hacktoberfest2020.

check this
https://github.com/zahinekbal/codeWith-hacktoberfest/issues/97#issue-715003561
nd check file format

**Comment by saipranay47** [comment]
sorry for that I have changed it now 

please suggest if there are any more changes 
I am hear to resolve them

**Comment by saipranay47** [comment]
please review my pull request @zahinekbal 

and I hear to solve if there is any issue

**Comment by zahinekbal** [comment]
This branch has conflicts that must be resolved

**Comment by saipranay47** [comment]
I had resolved them @zahinekbal

**Comment by saipranay47** [comment]
please merge it I am facing confits because you are merging the pr's of others before and they are changing readme.md @zahinekbal

**Pull request merged**
