### PR TITLE
added bubbleSort.py

### PR DESCRIPTION
**Pull request by JatinArora23**

### CODE REVIEW

**Comment by zahinekbal** [comment]
@JatinArora23 please use the file format

**Comment by JatinArora23** [comment]
Can you please elaborate what you mean?
Since thats my first contribution I'm not really sure of what i did is right or wrong.

**Comment by zahinekbal** [comment]
Okk no problem @JatinArora23 actually I declared file format in issues description kindly check itt I mentioned file format how you hv to assign it ohkk just check it ohkk.
Nd update your pr 
In case you are facing some problem then feel free to contact me ☺️

**Comment by JatinArora23** [comment]
@zahinekbal so you mean i just change the name format of file and push that again? Correct me if I'm wrong.

**Comment by zahinekbal** [comment]
Yeahhh 😊

**Pull request closed without merging**
