### PR TITLE
Add House Robber Algorithm in C++

### PR DESCRIPTION
**Pull request by anjali1903**
Added the code for the famous dynamic programming problem, House Robber

### CODE REVIEW

**Comment by zahinekbal** [comment]
> Added the code for the famous dynamic programming problem, House Robber

Please add your image in image folder nd update readme.md file this is for all contributors
do this then only i will be able to merge PR..
Check this
#90 (comment)

**Comment by anjali1903** [comment]
I'm sorry but I'm not very comfortable in sharing my own picture. Hope you would understand :)

**Comment by zahinekbal** [comment]
> I'm sorry but I'm not very comfortable in sharing my own picture. Hope you would understand :)
> Can I upload my current Github image?

Yeah sure upload your current GitHub image

**Comment by anjali1903** [comment]
Hi. I created a new pull request for img and READEME.md. Please check :)

**Pull request merged**
