### PR TITLE
Implementing Function strstr CPP

### PR DESCRIPTION
**Pull request by Palak0519**

### CODE REVIEW

**Comment by zahinekbal** [comment]
> _No description provided._

please use this file format nd then update your PR
### i.e:-  ImplementStrstr/CPP/ImplementFunctionStrstr.c++

**Comment by zahinekbal** [comment]
> > _No description provided._
> 
> please use this file format nd then update your PR
> 
> ### i.e:- ImplementStrstr/CPP/ImplementFunctionStrstr.c++

@Palak0519 read this

**Comment by Palak0519** [comment]
Sure, will do that!

**Comment by Palak0519** [comment]
> > > _No description provided._
> > 
> > 
> > please use this file format nd then update your PR
> > ### i.e:- ImplementStrstr/CPP/ImplementFunctionStrstr.c++
> 
> @Palak0519 read this

Made changes in #179 PR. Kindly review.

**Pull request closed without merging**
