### PR TITLE
algorithms added

### PR DESCRIPTION
**Pull request by sachin-611**

### CODE REVIEW

**Comment by zahinekbal** [comment]
@sachin-611 Can you use file format Eveything is right.

**Comment by sachin-611** [comment]
@zahinekbal  yes everything works fine on my machine!!

**Comment by sachin-611** [comment]
@zahinekbal  why you closed PR?

**Comment by zahinekbal** [comment]
Kindly use file format

**Comment by zahinekbal** [comment]
Update yor pr using file format I will merge then

**Comment by sachin-611** [comment]
@zahinekbal can you tell which file format?

**Comment by zahinekbal** [comment]
# SortingAlgorithm/C++/YourAlgorithm.extension..

**Pull request closed without merging**
